apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    name: webserver-service
spec:
  selector:
    app: webserver
  type: ClusterIP
  ports:
    - port: 80           # Porta interna do Service
      targetPort: 80       # Porta no Pod (container)
      #nodePort: 30080      # valor entre 30000–32767
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: k8s.local
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: webserver-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: goserver-service
                port:
                  number: 80
