apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: development
type: Opaque
data:
  username: YWRtaW4=          # base64 de "admin"
  password: c2VuaGExMjM=      # base64 de "senha123"
  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: mongo-db-deployment
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---

apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: mongo-db-service
  labels:
    app: mongo-db
spec:
  type: ClusterIP
  selector:
    app: mongo-db
  ports:
    - port: 27017           # Porta interna do Service
      targetPort: 27017       # Porta no Pod (container)
      #nodePort: 32017     # Porta externa entre 30000–32767
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
