apiVersion: v1
kind: Pod
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  containers:
    - name: goserver
      image: yamidudu/hello.go:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: 100Mi
        requests:
          cpu: "100m"
          memory: 100Mi
